server:
  port: 8086
spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
  datasource:
    url: "jdbc:postgresql://localhost:5432/accountsdb"
    username: "postgres"
    password: "postgres"
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: "optional:configserver:http://localhost:8071/accounts"

management:
  endpoints:
    web:
      exposure:
        include: "*"
